### PR TITLE
5th branch

### PR DESCRIPTION
**Pull request by vermasavita**
### What functionalities need to check?

- Explore the post page
- Feed Post Page
- Edit Profile
- Follow & Unfollow User
- Loader
- Post date

### CODE REVIEW

**Review by anupkgurung — APPROVED** [review]
Unfollow feature is not implemented.
Rest of functionality is fine

**Comment by vermasavita** [comment]
> Unfollow feature is not implemented. Rest of functionality is fine

Go to the profile page and click on following, list of following will be open and user can unfollow from there

**Review by prajapati-priyanka — APPROVED** [review]
Follow/Unfollow feature is not working as it should be. When a user is following any other user, then their posts should also start reflecting to your feed.
Look over it once.
Rest of the functionalities are working as intended.

**Comment by vermasavita** [comment]
> Follow/Unfollow feature is not working as it should be. When a user is following any other user, then their posts should also start reflecting to your feed. Look over it once. Rest of the functionalities are working as intended.

What issue are you facing in follow and unfollow functionality? 

For now, only user posts will be there in the feed. That's the functionality. I'll modify that later

**Pull request merged**
